# -*- coding: utf-8 -*-
"""Citizen AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmtyGkhE-jdl87CwAQAVj6WwGaF13e3-
"""

!pip install transformers torch gradio -q

from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline
import gradio as gr

# Load IBM Granite model
model_name = "ibm-granite/granite-3.2-2b-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

# Create pipeline
generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

# Chat function
def chat_with_ai(prompt):
    result = generator(prompt, max_length=200, temperature=0.7, do_sample=True)
    return result[0]['generated_text']

# Launch Gradio app
interface = gr.Interface(fn=chat_with_ai, inputs="text", outputs="text", title="Citizen AI Chatbot")
interface.launch(share=True)
